### ISSUE TITLE
Unable to use docker image

### ISSUE THREAD

**Issue by dashrandom** [intri-in/manage-my-damn-life-nextjs#170]
I'm getting the following error when using the docker image 

```
"Error connecting to database. Check your database settings. Here's some more information:

{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'mmdm_user'@'172.22.0.3' (using password: YES)"}"
```
I'm not sure why this error is occuring, considering that mmdm_user is not the user specified in the docker compose file or the .env file I'm using...

![image](https://github.com/intri-in/manage-my-damn-life-nextjs/assets/9287237/d30c59d9-0453-4c34-81ab-b5ca37e6cc00)

My docker compose is follows:

```
version: "2.6"
services:
  app:
    container_name: mmdl_app
    image: intriin/mmdl:latest
    ports:
      - 3001:3000
    depends_on:
      - db
    networks:
      - web
      - internal
    restart: unless-stopped
    environment:
      DB_HOST: db
#    env_file:
#      - .env.local
    extra_hosts:
    - "host.docker.internal:host-gateway"
  db:
    container_name: mmdl_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306
    networks:
#      - web
      - internal
    environment:
    ############################################################
    ## The following variables NEED to be set before execution.
    ############################################################
      #DB_NAME and MYSQL_DATABASE must be the same.
      MYSQL_DATABASE: mmdl
      # This is the user name and password of your mysql user that will be created. These values must be used in DB_USER and DB_PASS variables in the .env file that you will create.
      MYSQL_USER: mmdl
      MYSQL_PASSWORD: password
      # This defines the root password of mysql in the container. You can use the root user too. 
      MYSQL_ROOT_PASSWORD: password
    ############################################################
    ## The following variables are advanced settings,
    ## and must be only changed in case you're trying something
    ## specific.
    ############################################################
#      MYSQL_ALLOW_EMPTY_PASSWORD: ok
#      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  web:
    external: true
  internal:
    external: false
```
