### ISSUE TITLE
Database crashing instantly

### ISSUE THREAD

**Issue by DLBPointon** [intri-in/manage-my-damn-life-nextjs#251]
Morning @intri-in 

In an effort to de-google things, i've spend the past week looking for a calendar/to-do app to self host. Your app looks great and so far looks to tick all the boxes. However, I seem to have issues getting it running.

The database crashes immediately:
```
db-1   | 2025-06-05 08:09:42+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.3.0-1.el9 started.
db-1   | 2025-06-05 08:09:43+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db-1   | 2025-06-05 08:09:43+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.3.0-1.el9 started.
db-1   | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
db-1   | 2025-06-05T08:09:43.445249Z 0 [System] [MY-015015] [Server] MySQL Server - start.
db-1   | 2025-06-05T08:09:43.640021Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 9.3.0) starting as process 1
db-1   | 2025-06-05T08:09:43.645497Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db-1   | 2025-06-05T08:09:43.956071Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db-1   | mysqld: Table 'mysql.plugin' doesn't exist
db-1   | 2025-06-05T08:09:44.074996Z 0 [ERROR] [MY-010735] [Server] Could not open the mysql.plugin table. Please perform the MySQL upgrade procedure.
db-1   | 2025-06-05T08:09:44.075241Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
db-1   | 2025-06-05T08:09:44.075444Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
db-1   | 2025-06-05T08:09:44.075599Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
db-1   | 2025-06-05T08:09:44.075789Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
db-1   | 2025-06-05T08:09:44.075924Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
db-1   | 2025-06-05T08:09:44.076063Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
db-1   | 2025-06-05T08:09:44.076217Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
db-1   | 2025-06-05T08:09:44.166163Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
db-1   | 2025-06-05T08:09:44.246424Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
db-1   | 2025-06-05T08:09:44.255553Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db-1   | 2025-06-05T08:09:44.255612Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db-1   | 2025-06-05T08:09:44.261014Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db-1   | 2025-06-05T08:09:44.261721Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
db-1   | 2025-06-05T08:09:44.262076Z 0 [ERROR] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-001146 - Table 'mysql.component' doesn't exist
db-1   | 2025-06-05T08:09:44.262132Z 0 [Warning] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-003543 - The mysql.component table is missing or has an incorrect definition.
db-1   | 2025-06-05T08:09:44.262364Z 0 [ERROR] [MY-000067] [Server] unknown variable 'default-authentication-plugin=mysql_native_password'.
db-1   | 2025-06-05T08:09:44.264065Z 0 [ERROR] [MY-010119] [Server] Aborting
db-1   | 2025-06-05T08:09:45.830361Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 9.3.0)  MySQL Community Server - GPL.
db-1   | 2025-06-05T08:09:45.830379Z 0 [System] [MY-015016] [Server] MySQL Server - end.
db-1 exited with code 1
```

This is with as simple as a compose file as possible:

```
networks:
  app-tier:
    driver: bridge
services:
  app:
    image: intriin/mmdl:latest
    ports:
      - 3060:3000
    depends_on:
      - db
    networks:
      - app-tier
    restart: always
    environment:
      DB_HOST: db
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: sample_install_mmdm
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_HOST: "%"
```

I did start off with a compose file containing the suggested changes as in the docs, but still no luck. It seems as though the database isn't set up right?Is the Is there anything i'm missing?

Also, where is the DB being stored? in the other apps I run with a DB, there is normally a mount for a local directory. Something your project doesn't have. Is this something i've missed or isn't used at all?

Thanks again for a great project!
Damon

**Comment by intri-in** [comment]
Presently, mysql2, the library used under the hood in MMDL doesn't support Mysql >9. You can instead use MySQL 8 or any other DB like PostgreSQL to make it work. For an example, see https://github.com/intri-in/manage-my-damn-life-nextjs/issues/241#issuecomment-2936885502

**Comment by DLBPointon** [comment]
Thanks for the help, however, it hasn't worked for me.

I go to the login screen and get a ` Cant get registration status from server `, which to me sounds like I have a config wrong somewhere. I'm sticking with the not-recommended auth for the moment, I need to get up to speed on something like Authentik before adding that to the mix.

Could you have a look at the below and see where I've gone wrong, thanks.

My Docker file is now:
```
networks:
  app-tier:
    driver: bridge
services:
  app:
    image: intriin/mmdl:latest
    ports:
      - 3060:3000
    depends_on:
      - db
    networks:
      - app-tier
    restart: always
    environment:
      DB_HOST: db
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:8.4
    command: --mysql-native-password=ON
    restart: always
    expose:
      - 3306
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: mmdm_db
      MYSQL_USER: dlbpointon
      MYSQL_PASSWORD: SomethingSuperSecret
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_HOST: "%"
```

env:
```
DB_HOST=http://192.168.1.227
DB_USER=dlbpointon
DB_PASS=SomethingSuperSecret
DB_NAME=mmdm_db
DB_PORT=3306
DB_DIALECT=mysql
AES_PASSWORD=32-key-pass
NEXTAUTH_SECRET=another-32-keys
USE_NEXT_AUTH=true
NEXT_PUBLIC_USE_NEXT_AUTH=true
NEXTAUTH_URL=http://192.168.1.227:3060/
NEXT_PUBLIC_DISABLE_USER_REGISTRATION=false
MAX_CONCURRENT_LOGINS_ALLOWED=3
MAX_OTP_VALIDITY=1800
MAX_SESSION_LENGTH=2592000
ENFORCE_SESSION_TIMEOUT=true
DOCKER_INSTALL=true
NEXT_PUBLIC_API_URL=http://192.168.1.227:3060/api
NEXT_PUBLIC_DEBUG_MODE=true
NEXT_API_DEBUG_MODE=true
NEXT_PUBLIC_SUBTASK_RECURSION_CONTROL_VAR=100
NEXT_PUBLIC_TEST_MODE=false
```
