### ISSUE TITLE
client does not support authentication protocol requested by server, consider upgrading mysql client

### ISSUE THREAD

**Issue by unusualevent** [intri-in/manage-my-damn-life-nextjs#92]
the mysql docker image is unpinned so I'm not sure if this is related.

```
Error connecting to database. Check your database settings. Here's some more information:

{"code":"ER_NOT_SUPPORTED_AUTH_MODE","errno":1251,"sqlMessage":"Client does not support authentication protocol requested by server; consider upgrading MySQL client","sqlState":"08004","fatal":true}
```

```
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose: 
      - 3306
    networks:
      - app-tier
    environment:
```
